default: &default
  adapter: postgresql
  encoding: unicode
  username: sontn
  password: Son@1123
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: projrails_development

test:
  <<: *default
  database: projrails_test

production:
  <<: *default
  database: projrails_production
